Repository htacg/tidy-html5, pull requests merged in 2018-04, with the labels that each got.

#684 Update language_en.h
  src/language_en.h
Labels: Docs

#705 Is #673 - Revert 350f7b4 and 86e62db AdjustConfig logic
  src/config.c
  src/config.h
  src/tidylib.c
Labels: Bug

#712 Make global attribute `dir` accept auto as well.
  src/attrs.c
Labels: Feature Request

#722 Is #721 - cast away some gcc warnings
  console/tidy.c
Labels: Build/Install
