Repository htacg/tidy-html5, pull requests merged in 2020-10, with the labels that each got.

#830 Is. #761 - just deal with the 'uint' wrap
  src/lexer.c
Labels: Bug

#853 Protect against NULL in PruneSection.
  src/clean.c
Labels: Bug

#881 Complete pt_br translation
  localize/translations/language_pt_br.po
Labels: Docs, Infrastructure

#884 fix memleak in GetTokenFromStream
  src/lexer.c
Labels: Bug

#886 COMPILE_FLAGS property only once per target, avoid overwriting.
  CMakeLists.txt
Labels: Build/Install

#897 Correction for issue-895
  src/tags.c
Labels: Bug
