Repository htacg/tidy-html5, pull requests merged in 2020-11, with the labels that each got.

#848 Support the <slot> tag
  include/tidyenum.h
  src/attrdict.c
  src/attrdict.h
  src/attrs.c
  src/attrs.h
  src/tags.c
Labels: Feature Request, Help Needed, Technical Discussion

#898 Is. #896 - make 'bear' docs match code
  include/tidyenum.h
  src/clean.c
  src/language_en.h
  src/lexer.c
Labels: Bug, Docs

#899 Free attributes before return NULL
  src/lexer.c
Labels: Bug

#902 Is. #879: add loading attribute for img, iframe
  include/tidyenum.h
  src/attrdict.c
  src/attrs.c
Labels: Feature Request

#907 Add SVG paint attributes
  include/tidyenum.h
  src/attrdict.c
  src/attrs.c
  src/attrs.h
  src/tags.h
Labels: Feature Request
